spring.application.name=simulador

spring.datasource.url=jdbc:postgresql://db.cjpmrvmrkmilnqjqypvl.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=ProyectoDP1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
app.data-loader.enabled=false
