spring.application.name=genetico
spring.datasource.url=jdbc:mysql://db-dp1-instance.czxc1xdqb6cx.us-east-1.rds.amazonaws.com/tasf_b2b?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=dp114052026v1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
