spring.application.name=genetico
spring.datasource.url=jdbc:mysql://3.230.11.37:3306/tasf_b2b?
spring.datasource.username=tasf_user
spring.datasource.password=proyectotasfb2b2449!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
