spring.application.name=genetico
# --- NUEVA CONEXION A LA BD LOCAL EN LA VM ---
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/tasf_b2b?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=tasf_app
spring.datasource.password=Grupo7g@PUCP2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIONES DE HIBERNATE/JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIONES DE ARCHIVOS MULTIPART ---
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
#server.port=8080

# --- CONFIGURACIONES DE SEGURIDAD JWT ---
tasf.auth.jwt-secret=${TASF_AUTH_JWT_SECRET:change-this-dev-secret-before-production-please-keep-it-long}
tasf.auth.jwt-expiration-minutes=${TASF_AUTH_JWT_EXPIRATION_MINUTES:480}

spring.jackson.time-zone=UTC

# DEBEN CAMBIAR A UNA BD LOCAL, COMO POR EJEMPLO ESTA:

#spring.application.name=genetico
#spring.datasource.url=jdbc:mysql://db-dp1-instance.czxc1xdqb6cx.us-east-1.rds.amazonaws.com/tasf_b2b?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=dp114052026v1
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.servlet.multipart.max-file-size=500MB
#spring.servlet.multipart.max-request-size=500MB
#server.port=8080

#tasf.auth.jwt-secret=${TASF_AUTH_JWT_SECRET:change-this-dev-secret-before-production-please-keep-it-long}
#tasf.auth.jwt-expiration-minutes=${TASF_AUTH_JWT_EXPIRATION_MINUTES:480}